### ISSUE TITLE
Integration test pom dependencies & docker builds: Integration test pom shouldn't be strictly tied to spark pom

### ISSUE THREAD

**Issue by ssuchter** [apache-spark-on-k8s/spark-integration#2] opened 2017-12-14 00:04 UTC
Kimoon and I were just discussing a challenge with moving the integration tests out of the main spark repo into this spark-integration repo, and how we might solve this problem. I think this is related to or the same issue as something that Ilan was recently raising to our attention, I'm just trying to write down some concrete thoughts.

Currently, we have a profile in the main pom.xml called kubernetes-integration-tests that adds modules into the maven reactor inside resource-managers/kubernetes/. The intent of having the spark-integration repo is to not have that code inside the main spark repo anymore, but instead to be in the spark-integration repo. So therefore, this code cannot be part of the main spark maven reactor anymore.

If it's not part of the main spark maven reactor, it how has some complicated gyrations to build the docker images, in particular surrounding version numbers. Currently, the modules inside of resource-managers/kubernetes refer to their parent pom by exact version number. Since they're in the same repo, it's possible to atomically update all these references in one PR. But when they're inside two repos, we can't do that anymore, and this could lead to confusing test results when they mismatch. It also makes it hard to use the integration test repo against varying versions of the spark repo.

This could be solved by taking one bit outside of the maven build universe. Instead of having resource-managers/kubernetes/docker-minimal-bundle/pom.xml (or whatever its name is when inside the spark-integration repo) use a dependence on an exact version of the spark pom, let's make a non-maven script that takes the resulting spark distribution (e.g. a zip file) and build the dockers off of that. This script could be pointed to that zip file on the local filesystem, independent of maven dependencies. Then the spark-integration repo won't have to rely on a version number sync to the poms in the spark repo.

In this proposal, the spark-integration test repo could still have pom.xml files to build the integration test, and those may have dependencies on other artifacts. We just avoid any dependence on the exact version of the spark build under test.

Thoughts?

**Comment by ssuchter** [comment] 2017-12-14 00:08
@mccheah @kimoonkim @ifilonenko @foxish @felixcheung @shaneknapp - please take a look

**Comment by erikerlandson** [comment] 2017-12-14 00:31
SGTM - it makes it clean to understand what code is being built and why.

We do this in our container construction.  It actually allows for smaller images, since you can pull it from a remote, unpack it, and set permissions, etc in a single `RUN` command, w/out the `COPY`; unless we have to build the zip-file locally, in which case it will be closer to how it is now

**Comment by foxish** [comment] 2017-12-14 00:36
> let's make a non-maven script that takes the resulting spark distribution (e.g. a zip file) and build the dockers off of that.

+1. This decoupling is good IMO.

**Comment by mccheah** [comment] 2017-12-14 01:39
The maven reactor isn't building the docker images here, it just contains tasks to assemble the jars from all of Spark's dependencies into the same place and creates the build directory from which the integration test code itself builds the Docker images. See this class: https://github.com/apache-spark-on-k8s/spark/pull/521/files#diff-eed0a4fc50b402352f4fc7f107be9c82R37.

So as long as the integration test code has a directory to work with, however that directory is generated, the images can be built. The integration test code is not opinionated to version numbers that the jars in this directory have.

**Comment by foxish** [comment] 2017-12-14 01:51
There is still value in separating out the docker build flow as Sean mentioned. The way it builds images within the integration test code has so far made it harder to adapt it to testing in other environments outside minikube. So, I do think it's a step in the right direction to replace that code with scripts that do the required building and just have the integration test code use those images.

**Comment by ssuchter** [comment] 2017-12-14 01:56
I think Matt gave (for me, at least) a good clarification about what the reactor pom is being used for. The question I'd have is if the collecting of the jars really has to be done in maven, or could we just get them from the published .zip file from the spark repo. I haven't looked yet to see if they are all in there. If we could get them from the .zip file, then I'd change the wording of the central idea here to have a script that gets the jars out of that .zip file, rather than using maven dependencies to get the jars.

**Comment by mccheah** [comment] 2017-12-14 02:00
@ssuchter I don't know if the Spark pull request builder publishes snapshot zip files.

To @foxish 's point as well and more generally - I'm wondering if we actually have more flexibility in our build system if we put integration tests in a separate repository. For example, Maven isn't as elegant at arbitrary command execution in builds. We could use something like Gradle and use a plugin like [gradle-docker](https://github.com/palantir/gradle-docker) to handle building these images.

**Comment by mccheah** [comment] 2017-12-14 02:09
We can also clone the Spark repository under test and run `make-distribution.sh` to build our own distributions which guarantees we have the right Maven setup and that we don't have to incorporate any Maven magic ourselves. The point with Gradle is that it's easier to use that for arbitrary command execution and in particular to handle Docker images.

An alternative to using the build system to do the commands is to make the Jenkins job itself specify the commands, but I like having the commands in the integration test repo's build system code, because it's easier to edit them and the history is tracked by Git, etc. Ideally the build system should only specify a single command that runs "all the things", and having a build system with better support for tying commands to build lifecycle would get us closer to that end goal with more readable build code. Though I should note that it's only my personal opinion and experience to say that Gradle is the more readable and better-suited option here.

**Comment by ssuchter** [comment] 2017-12-14 02:26
Cloning the Spark repo under test and run make-distribution.sh seems like a pretty acceptable solution to me.

I definitely am not suggesting that we encode lots of complexity into Jenkins's scripts. I think that the complexity should be checked in, I don't care too much whether it's scripts or maven or gradle. What I am centrally trying to eliminate is the encoding of the dependence on the parent pom from the spark repo and the resulting version number equivalence requirement.

(Re: build tools: Heh, heh, I'm pretty partial to Bazel nowadays, but that's a whole new ball of wax.)

**Comment by mccheah** [comment] 2017-12-14 02:45
Yep makes sense - and the current setup only shares the version numbers because they're in the same repository, but once we have one repo clone the other the versions can be disjoint between them without any problems. The integration test runner needs to tag the image with a unique ID though so that they can be deleted after the tests finish without accidentally deleting images from any concurrent runs.

**Comment by ssuchter** [comment] 2017-12-14 18:54
So I think we've come to a good idea of what we could implement. But I have a expectation/timing concern. This is a little more complex than I was thinking yesterday. I'd be happy to work on it, but I (like Matt) am about to be out until after Xmas and won't make any progress until then. I'm concerned that getting this done will stretch into January as a result.

Can we live with that? Kimoon offered to help yesterday, but he has other things that he's working on as well, and with the increased complexity, he also expressed concern about getting it fully done by the end of the year.

**Comment by foxish** [comment] 2017-12-14 18:59
I'm afraid waiting till Jan might not let us realize the value of this effort for upstream. If @kimoonkim or @ifilonenko can help put the basic framework together before then, I can devote some cycles to getting it finished.

**Comment by shaneknapp** [comment] 2017-12-14 19:40
my schedule is tight next week (out of town, working intermittently), but i
will be back on the 26th and able to dedicate as much time is needed to
help out.

regarding this plan, it seems relatively cromulent and will get us over the
hump to get this deployed.

the only thing that really bothers me is that we can't (yet) test
k8s-specific PRs on the mainline spark branch(es) w/the spark pull request
builder.  i'm hoping to make progress on this and move it to the ubuntu
workers by EOY.

**Comment by kimoonkim** [comment] 2017-12-14 21:14
I think I could spend a few days before @ssuchter comes back. Let's see how far we can go.

**Comment by kimoonkim** [comment] 2017-12-15 17:32
There is one more dependency issue that is unrelated with building docker images. The scala code in the integration test suite is directly using Spark-on-K8s client scala code, for launching driver and executor pods.  Here's an example:

In [KubernetesSuite.scala](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/KubernetesSuite.scala)

```
...
  test("Use container-local resources without the resource staging server") {
    assume(testBackend.name == MINIKUBE_TEST_BACKEND)

    sparkConf.setJars(Seq(CONTAINER_LOCAL_HELPER_JAR_PATH))
    runSparkPiAndVerifyCompletion(CONTAINER_LOCAL_MAIN_APP_RESOURCE)
  }
...
 private def runSparkApplicationAndVerifyCompletion(
      appResource: MainAppResource,
      mainClass: String,
      expectedLogOnCompletion: Seq[String],
      appArgs: Array[String],
      otherPyFiles: Seq[String]): Unit = {
    val clientArguments = ClientArguments(
      mainAppResource = appResource,
      mainClass = mainClass,
      driverArgs = appArgs,
      otherPyFiles = otherPyFiles,
      hadoopConfDir = None)
    Client.run(sparkConf, clientArguments)
    val driverPod = kubernetesTestComponents.kubernetesClient
      .pods()
      .withLabel("spark-app-locator", APP_LOCATOR_LABEL)
      .list()
      .getItems
      .get(0)
    Eventually.eventually(TIMEOUT, INTERVAL) {
      expectedLogOnCompletion.foreach { e =>
        assert(kubernetesTestComponents.kubernetesClient
          .pods()
          .withName(driverPod.getMetadata.getName)
          .getLog
          .contains(e), "The application did not complete.")
      }
    }
  }
```

The `Client` in the line `Client.run(sparkConf, clientArguments)` is a part of the Spark distribution we want to test. And the location and code will vary across different test targets. For instance, the class is in the [Client.scala](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/Client.scala) file in our fork, but resides in the [KubernetesClientApplication.scala](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/KubernetesClientApplication.scala) file in the upstream.

We clearly want to decouple this dependency as well. Should we let the integration code just use spark-submit command line instead of scala client code? Would doing this decoupling as well be too much work to meet the December timeline? I personally don't know. Thoughts?

**Comment by erikerlandson** [comment] 2017-12-15 18:16
IIRC we brought this up earlier and there was a reason the Client was being invoked directly, related to picking up the environment in a certain way.

IMO it will be far easier to decouple if the tests are at the CLI `spark-submit` level.

Re: timeline I brought up the idea of pushing back to early january on dev@spark.  Holden seems amenable but I haven't had any other responses yet.

**Comment by kimoonkim** [comment] 2017-12-15 18:32
Ah, I didn't think about env vars. Do we know which env vars should be passed? Examples would be nice. Integration test code can pass specific env vars to spark-submit, but we need to know which ones.

Yes, I think using the CLI spark-submit level is the right way to go. We just want to estimate how much extra work that would be.

**Comment by mccheah** [comment] 2017-12-15 18:46
CLI spark-submit from the distribution can work here.

**Comment by mccheah** [comment] 2017-12-15 18:46
The main thing before was that we weren't guaranteed to have a full distribution making running the `spark-submit` command line script questionable. But now we're guaranteed to have a distribution so we should just run `spark-submit` from that.

**Comment by kimoonkim** [comment] 2017-12-15 21:19
@erikerlandson @mccheah Sounds good to me. I'll see how we can run `spark-submit`.

**Comment by kimoonkim** [comment] 2017-12-16 01:24
Good news. I was able to build some docker images off a distro tarball. I ended up reusing existing scala code, [SparkDockerImageBuilder.scala](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/docker/SparkDockerImageBuilder.scala) after unpacking the distro tarball in the directory structure that the builder expects. If you're curious, the code is at my fork, https://github.com/kimoonkim/spark-integration/tree/add-test-code/integration-test.

The next step is launching spark-submit.

**Comment by shaneknapp** [comment] 2017-12-16 01:35
i also have good news...  i set up a github PRB on my own spark branch and it seems to actually be building on our ubuntu worker:
https://rise.cs.berkeley.edu/jenkins/job/ubuntuSparkPRB/4

this is a pretty solid requirement, in my mind, for merging this k8s branch back in to the spark mainline.

IFF the build is stable and gives full coverage (currently R is not installed), i will also need to reimage a couple of the existing centos workers w/ubuntu before i move the PRB over.  this can happen before EOY.

i'd also like to get some additional eyes from databricks on the ubuntu build logs as well.

but:  PROGRESS!  :)

**Comment by mccheah** [comment] 2017-12-16 02:09
Very cool - @kimoonkim as mentioned before it's probably not ideal to be using the `SparkDockerImageBuilder` to create Docker images in the test execution itself - but I think it's acceptable to start with that and then move to something that's driven by the build framework in future iterations.

**Comment by mccheah** [comment] 2017-12-16 02:13
@kimoonkim took an extremely quick and brief look, but so far looks like what we expect. One thing though - if Apache isn't publishing snapshots for distributions, we'll need to have the runs instead check out / git fetch / git clone / etc. the head of master and build the distribution from that.

**Comment by kimoonkim** [comment] 2017-12-16 23:12
@mccheah Thanks for taking a look. Yes, Jenkins jobs will have to build the distribution to test from scratch in that case. I think this is acceptable. We can also make Jenkins jobs parameterized so that users can specify the test target github repo and branch.

**Comment by kimoonkim** [comment] 2017-12-16 23:25
Another good news. Tests pass now! The test suite now has only two test functions now with the barebone SparkPi. (I had to remove extra tests requiring resource staging server, http resource support, etc) But they pass against a distribution from our fork.
```
$ mvn clean integration-test  \
  -Dspark-distro-tgz=/Users/kimoonkim/Tmp/spark-2.2.0-k8s-0.5.0-bin-20171215-246b885508.tgz
...
[INFO] --- scalatest-maven-plugin:2.0.0:test (integration-test) @ spark-kubernetes-integration-tests_2.11 ---
Discovery starting.
Discovery completed in 164 milliseconds.
Run starting. Expected test count is: 2
KubernetesSuite:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
- Run SparkPi with no resources
- Run SparkPi with a very long application name.
Run completed in 3 minutes, 25 seconds.
Total number of tests run: 2
Suites: completed 2, aborted 0
Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

Next step is to build a distro from the upstream repo and run the integration test against it.

**Comment by foxish** [comment] 2017-12-16 23:35
Awesome..! Those 2 tests seem like a good start. Once tested, we could
probably add it to master on the Spark-integration repo?

**Comment by kimoonkim** [comment] 2017-12-16 23:47
Yes, I think I can send a PR to the spark-integration repo master branch from [my fork](https://github.com/kimoonkim/spark-integration/tree/add-test-code/integration-test).

However, I just found an issue with the upstream spark repo. I built a distro tarball from it and ran our integration tests, which failed because the distribution tarball does not have our Dockerfiles yet I confirmed the repo itself has Dockerfiles. It seems we'd need a PR modifying `make-distribution.sh` to copy them to the tarball. @foxish or @liyinan926 Do we plan to send such a PR soon?

**Comment by foxish** [comment] 2017-12-17 00:02
Yes, that's on my list, and tracked in the JIRA.

On Dec 16, 2017 3:47 PM, "Kimoon Kim" <notifications@github.com> wrote:

Yes, I think I can send a PR to the spark-integration repo master branch
from my fork
<https://github.com/kimoonkim/spark-integration/tree/add-test-code/integration-test>
.

However, I just found an issue with the upstream spark repo. I built a
distro tarball from it and ran our integration tests, which failed because
the distribution tarball does not have our Dockerfiles yet I confirmed the
repo itself has Dockerfiles. It seems we'd need a PR modifying
make-distribution.sh to copy them to the tarball. @foxish
<https://github.com/foxish> or @liyinan926 <https://github.com/liyinan926>
Do we plan to send such a PR soon?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark-integration/issues/2#issuecomment-352220166>,
or mute the thread

**Comment by kimoonkim** [comment] 2017-12-17 00:06
Ok. Then we can perhaps add temporary lines in the integration-test pom.xml to copy Dockerfiles from the repo source in place to the expected location.

**Comment by kimoonkim** [comment] 2017-12-17 00:20
I hacked make-distribution.sh in my clone. But the tests still fail with a permission error. 

>  1m		1m		1	kubelet, minikube	spec.containers{spark-kubernetes-driver}	WarningFailed			Error: failed to start container "spark-kubernetes-driver": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/opt/entrypoint.sh\\\\\\\": permission denied\\\"\\n\""}
  1m		1m		1	kubelet, minikube							WarningFailedSync		Error syncing pod
```

This looks like a real bug in the upstream repo. I think `entrypoint.sh` file in the upstream lacks the executable file permission bit. Our fork has the bit.
```
$ ls -l apache/spark/resource-managers/kubernetes/docker/src/main/dockerfiles/spark-base/entrypoint.sh
-rw-r--r--  1 kimoonkim  staff  1379 Dec 16 15:17 apache/spark/resource-managers/kubernetes/docker/src/main/dockerfiles/spark-base/entrypoint.sh
$ ls -l apache-spark-on-k8s/spark/resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/spark-base/entrypoint.sh
-rwxr-xr-x  1 kimoonkim  staff  1378 Aug 30 09:12 apache-spark-on-k8s/spark/resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/spark-base/entrypoint.sh
```

**Comment by kimoonkim** [comment] 2017-12-17 00:32
Ok, with the executable bit fixed as well, tests pass against the upstream repo! I think I can add  a temporary pom.xml hack for the executable bit hack.

**Comment by kimoonkim** [comment] 2017-12-17 00:56
Success! Added hacks for dockerfiles and entrypoint.sh. Tests pass against the main repo!
```
$ mvn clean integration-test  \
    -Dspark-distro-tgz=/Users/kimoonkim/Tmp/spark-2.3.0-SNAPSHOT-bin-20171216-0c8fca4608.tgz  \
    -Dspark-dockerfiles-dir=/Users/kimoonkim/src2/apache/spark/resource-managers/kubernetes/docker/src/main/dockerfiles
...

[INFO] --- scalatest-maven-plugin:2.0.0:test (integration-test) @ spark-kubernetes-integration-tests_2.11 ---
Discovery starting.
Discovery completed in 121 milliseconds.
Run starting. Expected test count is: 2
KubernetesSuite:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
- Run SparkPi with no resources
- Run SparkPi with a very long application name.
Run completed in 3 minutes, 38 seconds.
Total number of tests run: 2
Suites: completed 2, aborted 0
Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

Sending a PR to the integration-tests repo.

**Comment by foxish** [comment] 2017-12-17 01:13
Excellent Kimoon. The bug in upstream is also tracked - it's here in https://issues.apache.org/jira/browse/SPARK-22777

**Comment by mccheah** [comment] 2017-12-18 20:40
`entrypoint.sh` can just be marked as executable before checking it into the repository. Alternatively, the Dockerfile itself can execute: `RUN chmod +x /opt/entrypoint.sh` after the file is added.

**Comment by kimoonkim** [comment] 2017-12-18 23:29
With PR #3, I am trying to set up a build in Pepperdata Jenkins. Here, the challenge is that we are dealing with two repos: a spark repo for building a Spark distribution package, and our integration-test repo for running integration tests against the distribution package.

Jenkins supports github with a plugin ([github plugin link](https://wiki.jenkins.io/display/JENKINS/GitHub+Plugin)), used by existing CI jobs for our fork. So I was inclined to use the plugin too. But I don't know the plugin can support dealing with multiple repos in a single build. Does anyone know? Is this a good thing to try?

If the answer is no, then we can probably chain 2 Jenkins jobs, using a plugin ([pipeline plugin link](https://wiki.jenkins.io/display/JENKINS/Pipeline+Plugin)) The first job clones the spark repo, builds the distribution package and hand the output over to the second job, which will clone the integration-test repo, and run integration tests. I have some personal experience with this, but I wonder what others think. For instance, can Berkeley Jenkins also support pipelined jobs or is it a deadend?

**Comment by kimoonkim** [comment] 2017-12-19 01:19
Ok. I just hooked this in Jenkins, which is passing now: http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark%20repo/job/spark-integration/22/console

```
[INFO] --- scalatest-maven-plugin:1.0:test (integration-test) @ spark-kubernetes-integration-tests_2.11 ---
Discovery starting.
Discovery completed in 142 milliseconds.
Run starting. Expected test count is: 2
KubernetesSuite:
- Run SparkPi with no resources
- Run SparkPi with a very long application name.
Run completed in 4 minutes, 38 seconds.
Total number of tests run: 2
Suites: completed 2, aborted 0
Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

This Jenkins job copies the distro tarball from the other Jenkins job: http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark%20repo/job/build-spark-distribution/

**Comment by kimoonkim** [comment] 2017-12-19 02:04
> we can probably chain 2 Jenkins jobs, using a plugin (pipeline plugin link) 

Please never mind of the Jenkins pipeline plugin. Turns out we don't need it. Jenkins jobs can easily add a postbuild step that triggers other jobs. The current Jenkins job for PR #3 is using the postbuild step mechanism.

**Comment by shaneknapp** [comment] 2017-12-19 11:40
yeah, having jobs trigger other jobs is super easy.

**Comment by mccheah** [comment] 2017-12-19 19:54
I was thinking we weren't going to use a plugin and that the Jenkins job can periodically just run a bash script that `git clone` the two repositories, runs `make-distribution.sh` for Spark, and runs `build/mvn integration-test` on the other. But, if there's more sophisticated automation for this, we should bias towards that!

**Comment by kimoonkim** [comment] 2017-12-19 20:14
I believe the github plugin and chained jobs are pretty standard mechanisms in Jenkins world. Using chained jobs is nicer mainly because we can easily tell which part has failed and look at the individual logs. The github plugin for each job also shows the list of commits between successive runs, so we can guess which commits likely caused failures.

The combined shell script approach is still a possible alternative. I think we can keep that in mind in case we want more flexibility in the future.

**Comment by mccheah** [comment] 2017-12-19 20:58
Initially I was concerned that the code for building the distribution wouldn't be part of this repo, and that it would be opaque to anyone who is trying to interact with these builds.

But I can backtrack on such matters - the fact is that the Spark distribution isn't part of the integration test logic, but it's just a dependency of the integration tests themselves. We can think of them analogously to the Maven dependencies we take for a given project - the project being built takes the built artifacts for e.g. Guava for granted, instead of going through the trouble of building Guava from source. Therefore the tests in a similar way should have the semantics that Spark is a pre-built binary dependency and it assumes that some other component has created the package to test.

Ideally upstream Spark would be providing us with these tarballs, but in the absence of that we have to trigger this ourselves somewhere.

**Closed** 2017-12-20 12:20 UTC
